# Generated by Django 3.1.1 on 2020-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeimage',
            name='train_status',
            field=models.BooleanField(default=False),
        ),
    ]
