# Generated by Django 3.1.1 on 2020-09-11 02:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeeimage_train_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitioninfo',
            name='frame_url',
            field=models.ImageField(max_length=300, upload_to=api.models.recog_image_upload),
        ),
    ]
