# Generated by Django 3.1.1 on 2020-09-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200911_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recognitioninfo',
            old_name='frame_url',
            new_name='face_image',
        ),
        migrations.RemoveField(
            model_name='recognitioninfo',
            name='face_bbox',
        ),
    ]
