# Generated by Django 3.1.1 on 2020-09-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200911_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitioninfo',
            name='face_image',
        ),
    ]
