# Generated by Django 3.1.1 on 2020-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recognitioninfo_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='category',
            field=models.BooleanField(default=True),
        ),
    ]
